# [[headers]]
#   for = '/**'
#   [server.headers.values]
#     Content-Security-Policy = 'script-src localhost:1313'   # "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; font-src 'self' data:; connect-src 'self' https://www.google-analytics.com; frame-ancestors 'self';"
#     Referrer-Policy = 'strict-origin-when-cross-origin'     # 'same-origin'
#     X-Content-Type-Options = 'nosniff'
#     X-Frame-Options = 'DENY'                                #'SAMEORIGIN'
#     X-XSS-Protection = '1; mode=block'
#     #? Feature-Policy = 'geolocation none; midi none; sync-xhr none; microphone none; camera none; magnetometer none; gyroscope none; speaker self; vibrate none; fullscreen self; payment none;'
# [[redirects]]
#   force = false
#   from = '/myspa/**'
#   status = 200
#   to = '/myspa/'
# [[redirects]]
#   from = "/**"
#   to = "/404.html"
#   status = 404
